//---------------------------------------------------------------------------

#ifndef Unit1H
#define Unit1H
//---------------------------------------------------------------------------

#include <Classes.hpp>
#include <Controls.hpp>
#include <StdCtrls.hpp>
#include <Forms.hpp>
#include <ExtCtrls.hpp>
#include <Graphics.hpp>

//---------------------------------------------------------------------------

class TForm1 : public TForm
{
__published:	// IDE-managed Components (auto-generated by the IDE)
    TShape *background;       // Background of the game area
    TImage *ball;             // Ball in the game
    TTimer *ballTimer;        // Timer controlling ball movement
    TImage *paddle;           // Paddle controlled by the player
    TTimer *moveLeftTimer;    // Timer for moving the paddle left
    TTimer *moveRightTimer;   // Timer for moving the paddle right
    TButton *startButton;     // Button to start/restart the game

    // Brick images (auto-generated)
    TImage *brick1;
    TImage *brick2;
    TImage *brick3;
    TImage *brick4;
    TImage *brick5;
    TImage *brick6;
    TImage *brick7;
    TImage *brick8;
    TImage *brick9;
    TImage *brick10;
    TImage *brick11;
    TImage *brick12;

    // Event handler methods
    void __fastcall ballTimerEvent(TObject *Sender);
    void __fastcall moveLeftTimerEvent(TObject *Sender);
    void __fastcall moveRightTimerEvent(TObject *Sender);
    void __fastcall onKeyDown(TObject *Sender, WORD &Key, TShiftState Shift);
    void __fastcall onKeyUp(TObject *Sender, WORD &Key, TShiftState Shift);
    void __fastcall onStartButtonClick(TObject *Sender);

private:	// User declarations

public:		// User declarations
    __fastcall TForm1(TComponent* Owner);
};

//---------------------------------------------------------------------------

extern PACKAGE TForm1 *Form1;

//---------------------------------------------------------------------------
#endif
